"""
SQLAlchemy model for the market_briefs table.
Stores the daily pre-market research brief generated by the Research Agent.
"""

from __future__ import annotations

from datetime import date, datetime, time

from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    Float,
    String,
    Text,
    Time,
    func,
)
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.orm import Mapped, mapped_column

from core.database import Base


class MarketBrief(Base):
    """Daily pre-market research brief produced by the Research Agent."""

    __tablename__ = "market_briefs"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    generated_at: Mapped[time] = mapped_column(Time, nullable=False)
    market_bias: Mapped[str] = mapped_column(String(10), nullable=False)  # BULLISH / BEARISH / NEUTRAL
    bias_confidence: Mapped[float] = mapped_column(Float, nullable=False)
    sgx_nifty_signal: Mapped[str] = mapped_column(String(20), nullable=True)
    fii_signal: Mapped[str] = mapped_column(String(20), nullable=True)
    dxy_signal: Mapped[str] = mapped_column(String(30), nullable=True)
    us_markets_signal: Mapped[str] = mapped_column(String(20), nullable=True)
    watchlist: Mapped[dict] = mapped_column(JSON, nullable=True)  # JSON array of stock names
    avoid_list: Mapped[dict] = mapped_column(JSON, nullable=True)  # JSON array of stock names
    recommended_stance: Mapped[str] = mapped_column(String(30), nullable=True)
    raw_json: Mapped[dict] = mapped_column(JSON, nullable=False)  # full Market Brief blob
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    def __repr__(self) -> str:
        return f"<MarketBrief date={self.date} bias={self.market_bias} conf={self.bias_confidence}>"
